### ISSUE TITLE
Outer bracket for commutators

### ISSUE THREAD

**Issue by abunickabhi** [nbwzx/commutator#1]
Currently the algs are decomposed as A:[B,C].

It would be convenient if it is decomposed as [A:[B,C]] so that it is easy to enter into the alg.cubing.net site.

**Comment by nbwzx** [comment]
Good idea! Many people in China prefer the commutator notion without an outer bracket. But sometimes the commutator notion with an outer bracket would be more convenient. I think settings can be provided to customize the output format.

**Comment by nbwzx** [comment]
Now you can change the output format to "Outer bracket for all commutators". Just open the website and try out!

**Comment by abunickabhi** [comment]
Thanks, it works!
